// <auto-generated />
namespace IssueLog_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addproject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addproject));
        
        string IMigrationMetadata.Id
        {
            get { return "201902240743485_add project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
