// <auto-generated />
namespace IssueLog_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addproject2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addproject2));
        
        string IMigrationMetadata.Id
        {
            get { return "201902240757567_add project 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
